# Generated by Django 3.0.3 on 2020-02-19 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='company',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='ended_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.Resume'),
        ),
        migrations.AlterField(
            model_name='career',
            name='started_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='language',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='link',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.User'),
        ),
    ]
