# Generated by Django 3.0.3 on 2020-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20200219_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
